config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'dashboard#index'
  get 'profile', to: 'profile#show'
  get 'up' => 'rails/health#show', as: :rails_health_check

  # -- Expense
  post 'expenses', to: 'expense#create', as: :create_expense
  delete 'expenses/:id', to: 'expense#destroy', as: :delete_expense
  get 'expenses', to: 'expense#index', as: :expenses
  get 'expenses/:id/edit', to: 'expense#edit', as: :edit_expense
  patch 'expenses/:id', to: 'expense#update', as: :update_expense

  # -- Budgeting Goal
  post 'budgeting_goals', to: 'budgeting_goal#create', as: :create_budgeting_goal
  delete 'budgeting_goals/:id', to: 'budgeting_goal#destroy', as: :delete_budgeting_goal
  get 'budgeting_goals', to: 'budgeting_goal#index', as: :budgeting_goals
  get 'budgeting_goals/:id/edit', to: 'budgeting_goal#edit', as: :edit_budgeting_goal
  patch 'budgeting_goals/:id', to: 'budgeting_goal#update', as: :update_budgeting_goal
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budgeting_goal.rb
class BudgetingGoal < ApplicationRecord
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :category, presence: true
  validates :amount, presence: true
end

app/models/income_source.rb
class IncomeSource < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource_or_scope)
    return root_path # CHANGE HERE FOR REDIRECT
  end
end

app/controllers/budgeting_goal_controller.rb
class BudgetingGoalController < ApplicationController
  def index
    @budgeting_goals = BudgetingGoal.all
  end

  def create
    budgeting_goal = BudgetingGoal.new(budgeting_goal_params)

    if budgeting_goal.save
      redirect_to root_path, notice: 'Budgeting goal was successfully created.'
    else
      flash.now[:error] = 'Budgeting goal was not created.'
      render 'dashboard/index'
    end
  end

  private
  def budgeting_goal_params
    params.require(:budgeting_goal).permit(:name, :amount, :start_date, :end_date)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = current_user
    @expense = Expense.new
    @expenses = Expense.all
    @budgeting_goals = BudgetingGoal.all
    @budgeting_goal = BudgetingGoal.new

  end
end

app/controllers/expense_controller.rb
# frozen_string_literal: true

class ExpenseController < ApplicationController
  def index
    @expenses = Expense.all
  end

  def create
    @expense = Expense.new(expense_params)

    puts @expense.inspect

    if @expense.save
      redirect_to root_path, notice: 'Expense was successfully created.'
    else
      flash.now[:notice] = 'Expense could not be created.'
      render 'dashboard/index', status: :unprocessable_entity
    end
  end

  def destroy
    @expense = Expense.find(params[:id])

    if @expense.destroy
      redirect_to root_path, notice: 'Expense was successfully deleted.'
    else
      flash.now[:notice] = 'Expense could not be deleted.'
      render 'dashboard/index', status: :unprocessable_entity
    end
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def update
    @expense = Expense.find(params[:id])

    if @expense.update(expense_params)
      redirect_to root_path, notice: 'Expense was successfully updated.'
    else
      flash.now[:notice] = 'Expense could not be updated.'
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :date, :category)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def check
    val = ActiveRecord::Base.connection.execute('select 1+2 as val').first['val']
    render plain: "1+2=#{val}"

    value = ENV.fetch('RAILS_ENV') # raises
    ENV['RAILS_ENV'] # doesnt raise, simply nil
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgeting_goal_helper.rb
module BudgetingGoalHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/expense_helper.rb
module ExpenseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/dashboard/_budgeting_goal_item.html.erb
<li class="bg-zinc-100 p-4 rounded-lg mb-2">
    <h2 class="text-xl font-semibold text-blue-500"><%= budgeting_goal.name %></h2>
    <p class="text-gray-700">Amount: <%= budgeting_goal.amount %></p>
    <p class="text-gray-700">Category: <%= budgeting_goal.category %></p>
    <p class="text-gray-700">Date: <%= budgeting_goal.date %></p>
    
    <div class="flex space-x-2">
        <%= link_to 'Edit', edit_budgeting_goal_path(budgeting_goal), class: 'bg-blue-500 text-white px-4 py-2 rounded-lg mt-2' %>
        <%= button_to 'Delete', delete_budgeting_goal_path(budgeting_goal), method: :delete, data: { confirm: 'Are you sure?' }, class: 'bg-red-500 text-white px-4 py-2 rounded-lg mt-2' %>
    </div>
</li>

app/views/dashboard/_expense_item.html.erb
<li class="bg-zinc-100 p-4 rounded-lg mb-2">
    <h2 class="text-xl font-semibold text-blue-500"><%= expense.name %></h2>
    <p class="text-gray-700">Amount: <%= expense.amount %></p>
    <p class="text-gray-700">Category: <%= expense.category %></p>
    <p class="text-gray-700">Date: <%= expense.date %></p>
    
    <div class="flex space-x-2">
        <%= link_to 'Edit', edit_expense_path(expense), class: 'bg-blue-500 text-white px-4 py-2 rounded-lg mt-2' %>
        <%= button_to 'Delete', delete_expense_path(expense), method: :delete, data: { confirm: 'Are you sure?' }, class: 'bg-red-500 text-white px-4 py-2 rounded-lg mt-2' %>
    </div>
</li>

app/views/dashboard/index.html.erb
<h1 class="text-3xl text-blue-500">Finman - FOSS Finance Manager</h1>
<div class="flex flex-col gap-4 mt-4" data-controller="dashboard">
  
  <div class="flex flex-row gap-4" data-controller="dashboard">
    <%= render 'dashboard/modals/new_expense' %>
    <%= render 'dashboard/modals/new_budgeting_goal' %>
    <%= render 'dashboard/modals/new_income_source' %>
    <section class="bg-zinc-100 p-4 rounded-lg min-h-max w-1/2">
      <div class="flex flex-col md:flex-row items-start md:items-center justify-between">
        <div class="w-full m-0 p-0">
          <h1 class="text-2xl text-left font-semibold mb-2">Budget</h1>
          <ul class="space-y-2">
            <li>
              <button data-action="dashboard#showNewExpenseModal" class="text-white bg-blue-600 hover:bg-blue-700 transition duration-300 linear p-2 rounded-lg">
                + New Expense
              </button>
            </li>
            <li>
              <button data-action="dashboard#showNewBudgetingGoalModal" class="text-white bg-blue-600 hover:bg-blue-700 transition duration-300 linear p-2 rounded-lg">
                + New Budgeting Goal
              </button>
            </li>
            <li>
              <button data-action="dashboard#showNewIncomeSourceModal" class="text-white bg-blue-600 hover:bg-blue-700 transition duration-300 linear p-2 rounded-lg">
                + New Income Source
              </button>
            </li>
          </ul>
        </div>
        <div class="mt-4 md:mt-0">
          <div class="border-4 border-sky-600 p-16 md:p-8 rounded-xl">
            CHART
          </div>
        </div>
      </div>
    </section>
    
    <section class="bg-zinc-100 p-4 rounded-lg h-fit w-1/2">
      <div class="border-4 border-sky-600 rounded-xl p-16 md:p-40">
        CHART
      </div>
    </section>
  </div>

  <div class="flex flex-row gap-4">
    <section class="bg-zinc-100 p-4 rounded-lg w-full">
      <h1 class="text-2xl text-left font-semibold mb-2">Expenses</h1>
      <ul>
        <% Expense.all.each do |expense| %>
          <%= render "dashboard/expense_item", expense: expense %>
        <% end %>
      </ul>
    </section>
  </div>
</div>

app/views/dashboard/modals/_new_budgeting_goal.html.erb
<div data-dashboard-target="newBudgetingGoalModal" class="fixed inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center z-50 hidden">
  <div class="bg-white rounded-lg p-6 w-full max-w-md">
    <h2 class="text-2xl font-semibold text-blue-500 mb-4">Add New Budgeting Goal</h2>
    <%= form_for @budgeting_goal, url: create_budgeting_goal_path, method: :post, local: true, data: { turbo: false } do |form| %>
      <div class="mb-4">
        <%= form.label :name, "Goal Name", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_field :name, id: "goalName", placeholder: "Enter goal name", class: "w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
      <div class="mb-4">
        <%= form.label :amount, "Target Amount", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.number_field :amount, id: "goalAmount", placeholder: "Enter target amount", class: "w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
      <div class="mb-4">
        <%= form.label :start_date, "Start Date", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.date_field :start_date, id: "goalStartDate", class: "w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
      <div class="mb-4">
        <%= form.label :end_date, "End Date", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.date_field :end_date, id: "goalEndDate", class: "w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
      <div class="flex justify-end">
        <button type="button" class="bg-gray-500 text-white px-4 py-2 rounded-lg mr-2" data-action="dashboard#closeNewBudgetingGoalModal">Cancel</button>
        <button type="submit" class="bg-blue-600 text-white px-4 py-2 rounded-lg">Add Goal</button>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/modals/_new_expense.html.erb
<div data-dashboard-target="newExpenseModal" class="fixed inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center z-50 hidden">
  <div class="bg-white rounded-lg p-6 w-full max-w-md">
    <h2 class="text-2xl font-semibold text-blue-500 mb-4">Add New Expense</h2>
    <%= form_for @expense, url: create_expense_path, method: :post, local: true, data: { turbo: false }  do |form| %>
      <div class="mb-4">
        <%= form.label :name, "Expense Name", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_field :name, id: "name", placeholder: "Enter expense name", class: "w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
      <div class="mb-4">
        <%= form.label :date, "Date", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.date_field :date, id: "date", class: "w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
      <div class="mb-4">
        <%= form.label :amount, "Amount", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.number_field :amount, id: "amount", placeholder: "Enter amount", class: "w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
      <div class="mb-4">
        <%= form.label :category, "Category", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.select :category, options_for_select(["Utility", "Technology", "Food"]), { prompt: "Select a category" }, { id: "expenseCategory", class: "w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" } %>
      </div>
      <div class="flex justify-end">
        <button type="button" class="bg-gray-500 text-white px-4 py-2 rounded-lg mr-2" data-action="dashboard#closeNewExpenseModal">Cancel</button>
        <%= form.submit "Add Expense", class: "bg-blue-600 text-white px-4 py-2 rounded-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/modals/_new_income_source.html.erb
<div data-dashboard-target="newIncomeSourceModal" class="fixed inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center z-50 hidden">
  <div class="bg-white rounded-lg p-6 w-full max-w-md">
    <h2 class="text-2xl font-semibold text-blue-500 mb-4">Add New Income Source</h2>
    <form>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="incomeSourceName">Income Source Name</label>
        <input id="incomeSourceName" type="text" placeholder="Enter income source name" class="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="incomeAmount">Amount</label>
        <input id="incomeAmount" type="number" placeholder="Enter amount" class="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="interval">Interval</label>
        <select id="interval" class="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
          <option value="daily">Daily</option>
          <option value="weekly">Weekly</option>
          <option value="monthly">Monthly</option>
          <option value="annually">Annually</option>
          <option value="one-time">One Time</option>
        </select>
      </div>
      <div class="flex justify-end">
        <button type="button" class="bg-gray-500 text-white px-4 py-2 rounded-lg mr-2" data-action="dashboard#closeNewIncomeSourceModal">Cancel</button>
        <button type="submit" class="bg-blue-600 text-white px-4 py-2 rounded-lg">Add Income</button>
      </div>
    </form>
  </div>
</div>

app/views/expense/edit.html.erb
<%= form_for @expense, url: update_expense_path(@expense), method: :patch, class: "max-w-lg mx-auto bg-white p-6 rounded-lg shadow-md" do |f| %>
  
  <h1 class="text-2xl font-bold text-blue-500 mb-4">Edit Expense</h1>
  
  <div class="mb-4">
    <%= f.label :name, "Expense Name", class: "block text-gray-700" %>
    <%= f.text_field :name, class: "w-full p-2 border border-gray-300 rounded-lg" %>
  </div>

  <div class="mb-4">
    <%= f.label :amount, "Amount", class: "block text-gray-700" %>
    <%= f.number_field :amount, class: "w-full p-2 border border-gray-300 rounded-lg" %>
  </div>

  <div class="mb-4">
    <%= f.label :category, "Category", class: "block text-gray-700" %>
    <%= f.text_field :category, class: "w-full p-2 border border-gray-300 rounded-lg" %>
  </div>

  <div class="mb-4">
    <%= f.label :date, "Date", class: "block text-gray-700" %>
    <%= f.date_select :date, class: "w-full p-2 border border-gray-300 rounded-lg" %>
  </div>

  <div class="flex items-center justify-between">
    <%= f.submit "Update Expense", class: "bg-blue-500 hover:bg-blue-600 transition linear duration-300 cursor-pointer text-white px-4 py-2 rounded-lg" %>
    <%= link_to 'Cancel', root_path, class: "text-blue-500 underline" %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finman</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="flex justify-center">
      <%= render partial: 'shared/navbar' %>
    </div>
    <div class="flex justify-center">
      <% if flash[:notice] %>
        <div class="w-2/3 mt-4 p-4 bg-blue-100 border-l-4 border-blue-500 text-blue-700 rounded" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="w-2/3 mt-4 p-4 bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700 rounded" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
    <div class="px-20 py-6">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="w-2/3 relative px-4 py-4 flex justify-between items-center bg-white">
  <!-- Logo aligned to the left -->
  <a href="<%= root_path %>" class="text-3xl flex-start text-left font-bold mx5 leading-none">
    Finman
  </a>
  <!-- Spacer to push the desktop menu to the right -->
  <!-- Desktop menu -->
  <%= render "shared/_navbar/desktop_menu" %>
  <!-- Mobile menu -->
  <div class="mobile-menu hidden lg:hidden">
    <%= render "shared/_navbar/mobile_menu" %>
  </div>
</nav>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const burger = document.querySelector(".navbar-burger");
    const menu = document.querySelector(".mobile-menu");

    burger.addEventListener("click", function () {
      menu.classList.toggle("hidden");
    });
  });
</script>

app/views/shared/_navbar/_desktop_menu.html.erb
<div class="relative px-4 py-4 flex justify-between items-center bg-white">
  <!-- Logo aligned to the left -->
  <div class="flex items-center">
    <%= link_to root_path, id: "sad", class: "text-3xl font-bold leading-none" do %>
      <svg height="50px" width="200px" viewBox="0 0 112 112" fill="#000000" xmlns="http://www.w3.org/2000/svg">
        <!-- SVG content here -->
      </svg>
    <% end %>
  </div>
  <!-- Navbar content -->
  <div class="flex flex-end justify-end items-center w-full">
    <div class="lg:hidden">
      <button class="navbar-burger flex items-center text-blue-600 p-3">
        <svg class="block h-4 w-4 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <title>Mobile menu</title>
          <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
        </svg>
      </button>
    </div>
    <div class="hidden lg:flex lg:items-center lg:space-x-6">
      <ul class="flex items-center space-x-6">
        <% unless current_user.nil? %>
          <li>
            <%= link_to "Dashboard", root_path, class: "text-sm text-gray-400 hover:text-gray-500" %>
          </li>
          <li class="text-gray-300">
            <%= render partial: "shared/three_dots" %>
          </li>
        <% else %>
          <li>
            <%= link_to "About Us", "#", class: "text-sm text-gray-400 hover:text-gray-500" %>
          </li>
          <li class="text-gray-300">
            <%= render partial: "shared/three_dots" %>
          </li>
          <li>
            <%= link_to "Services", "#", class: "text-sm text-gray-400 hover:text-gray-500" %>
          </li>
          <li class="text-gray-300">
            <%= render partial: "shared/three_dots" %>
          </li>
          <li>
            <%= link_to "Contact", "#", class: "text-sm text-gray-400 hover:text-gray-500" %>
          </li>
          <li class="text-gray-300">
            <%= render partial: "shared/three_dots" %>
          </li>
        <% end %>
      </ul>
      <!-- User-specific Links -->
      <% if current_user.nil? %>
        <%= render "shared/_navbar/logged_out" %>
      <% else %>
        <%= render "shared/_navbar/logged_in" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar/_logged_in.html.erb
<div class="flex items-center space-x-4">
  <%= link_to "My Profile", profile_path, class: "py-2 px-6 bg-blue-500 hover:bg-blue-600 text-sm text-white font-bold rounded-xl transition duration-200" %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "py-2 px-6 bg-gray-50 hover:bg-gray-100 text-sm text-gray-900 font-bold rounded-xl transition duration-200" %>
</div>

app/views/shared/_navbar/_logged_out.html.erb
<div class="flex items-center space-x-4">
  <%= link_to "Sign In", user_session_path, class: "py-2 px-6 bg-gray-50 hover:bg-gray-100 text-sm text-gray-900 font-bold rounded-xl transition duration-200" %>
  <%= link_to "Sign Up", new_user_registration_path, class: "py-2 px-6 bg-blue-500 hover:bg-blue-600 text-sm text-white font-bold rounded-xl transition duration-200" %>
</div>

app/views/shared/_navbar/_menu_items.html.erb
<ul class="flex flex-col lg:flex-row lg:space-x-6">
  <li>
    <%= link_to "Dashboard", root_path, class: "text-sm text-gray-400 hover:text-gray-500" %>
  </li>
  <li class="text-gray-300">
    <%= render partial: "shared/three_dots" %>
  </li>
  <li><%= link_to "About Us", "#", class: "text-sm text-gray-400 hover:text-gray-500" %></li>
  <li class="text-gray-300">
    <%= render partial: "shared/three_dots" %>
  </li>
  <li><%= link_to "Services", "#", class: "text-sm text-gray-400 hover:text-gray-500" %></li>
  <li class="text-gray-300">
    <%= render partial: "shared/three_dots" %>
  </li>
  <li><%= link_to "Contact", "#", class: "text-sm text-gray-400 hover:text-gray-500" %></li>
</ul>

app/views/shared/_navbar/_mobile_menu.html.erb
<!-- Backdrop -->
<div id="backdrop" class="fixed inset-0 bg-black bg-opacity-50 hidden" aria-hidden="true"></div>
<!-- Mobile Menu Dialog -->
<div id="mobile-menu" class="fixed inset-0 z-50 flex items-center justify-center bg-white transform transition-transform duration-300 translate-x-full" aria-hidden="true">
  <div class="w-full max-w-xs p-4 bg-gray-100 shadow-lg">
    <button id="close-menu" class="absolute top-2 right-2 text-gray-500 hover:text-gray-700">
      &times;
    </button>
    <ul>
      <li>
        <%= link_to "Dashboard", root_path, class: "block text-sm text-gray-400 hover:text-gray-500" %>
      </li>
      <% if current_user.nil? %>
        <li>
          <%= link_to "About Us", "#", class: "block text-sm text-gray-400 hover:text-gray-500" %>
        </li>
        <li>
          <%= link_to "Services", "#", class: "block text-sm text-gray-400 hover:text-gray-500" %>
        </li>
        <li>
          <%= link_to "Contact", "#", class: "block text-sm text-gray-400 hover:text-gray-500" %>
        </li>
      <% end %>
      <% unless current_user.nil? %>
        <li>
          <%= link_to "Logout", destroy_user_session_path, class: "block py-2 px-4 text-sm text-gray-900 font-bold" %>
        </li>
        <li>
          <%= link_to "My Profile", profile_path, class: "block py-2 px-4 text-sm text-white bg-blue-500 hover:bg-blue-600 font-bold rounded-xl" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", user_session_path, class: "block py-2 px-4 text-sm text-gray-900 font-bold bg-gray-50 hover:bg-gray-100 rounded-xl" %>
        </li>
        <li>
          <%= link_to "Sign Up", new_user_registration_path, class: "block py-2 px-4 text-sm text-white bg-blue-500 hover:bg-blue-600 font-bold rounded-xl" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<!-- Trigger Button -->
<button id="open-menu" class="p-2 text-gray-500 hover:text-gray-700">
  Menu
</button>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    const openMenuButton = document.querySelector('.navbar-burger');
    const closeMenuButton = document.getElementById('close-menu');
    const mobileMenu = document.getElementById('mobile-menu');
    const backdrop = document.getElementById('backdrop');

    openMenuButton.addEventListener('click', function() {
      mobileMenu.classList.remove('translate-x-full');
      mobileMenu.classList.add('translate-x-0');
      backdrop.classList.remove('hidden');
    });

    closeMenuButton.addEventListener('click', closeMenu);
    backdrop.addEventListener('click', closeMenu);

    function closeMenu() {
      mobileMenu.classList.add('translate-x-full');
      mobileMenu.classList.remove('translate-x-0');
      backdrop.classList.add('hidden');
    }
  });
</script>

app/views/shared/_three_dots.html.erb
<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" class="w-4 h-4 current-fill" viewBox="0 0 24 24">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
</svg>